---
development:
  cloud_name: dvrks9u8i
  api_key: '324627132578373'
  api_secret: Xq_NbVPtcVfTJHeqw4u4PyO0iqE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dvrks9u8i
  api_key: '324627132578373'
  api_secret: Xq_NbVPtcVfTJHeqw4u4PyO0iqE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dvrks9u8i
  api_key: '324627132578373'
  api_secret: Xq_NbVPtcVfTJHeqw4u4PyO0iqE
  enhance_image_tag: true
  static_image_support: false
